hpformapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import formfunc

app_name = 'hpformapp'

urlpatterns = [
    path('form/', formfunc, name='form'),
]

instaformapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import formfunc,privacypolicyfunc,termsfunc,rootfunc

app_name = 'instaformapp'
urlpatterns = [
    path('form/', formfunc, name='form'),
    path('privacy-policy',privacypolicyfunc, name='privacy-policy'),
    path('terms',termsfunc, name='terms'),
    path('',rootfunc, name='root'),
]

onepageformproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://js.pay.jp/v2/pay.js"></script>

      {% block customcss %}
      {% endblock customcss %}

    <title>one-page-from</title>
  </head>
  <body>
    {% block header %}
    {% endblock header %}

    {% block content %}
    {% endblock content %}

  </body>
</html>

templates/hp_form.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <div>
    <label for="email">ご連絡先メールアドレス</label>
    <input type="email" id="email" name="email">
  </div>
  <div>
    <label for="pass">パスワード</label>
    <input type="password" id="password" name="password">
  </div>
  <div>
    <p>依頼内容</p>
    <label for="True">新規製作</label>
    <input type="radio" id="True" name="new" value="True"><br>
    <label for="False">リニューアル</label>
    <input type="radio" id="False" name="new" value="False">
  </div>
  <div>
    <label for="site_url">現サイトURL</label>
    <input type="url" id="site_url" name="site_url">
  </div>
  <div>
    <label for="company_name">会社（店舗）名</label>
    <input type="text" id="company_name" name="company_name">
  </div>
  <div>
    <label for="manager_name">担当者名</label>
    <input type="text" id="manager_name" name="manager_name">
  </div>
  <div>
    <label for="phone">日中ご連絡先電話番号</label>
    <input type="text" id="phone" name="phone">
  </div>
  <div>
    <label for="post">郵便番号</label>
    <input type="text" id="post" name="post">
  </div>
  <div>
    <label for="address">住所</label>
    <input type="text" id="address" name="address">
  </div>
  <div>
    <label for="company_overview">会社（店舗）概要</label>
    <input type="text" id="company_overview" name="company_overview">
  </div>
  <div>
    <label for="hope_domain">希望ドメイン</label>
    <input type="text" id="hope_domain" name="hope_domain">
  </div>
  <div>
    <label for="site_image">サイト希望イメージ</label>
    <select multiple name="site_image" id="site_image">
    <option value="kind">優しい</option>
    <option value="warm">暖かい</option>
    <option value="lively">にぎやか</option>
    <option value="calm">落ち着きのある</option>
    <option value="japanese_style">和風</option>
    <option value="deluxe">高級な</option>
    <option value="others">その他</option>
  </select>
</div>
  <div>
    <label for="site_image_text">希望イメージのその他</label>
    <input type="text" id="site_image_text" name="site_image_text">
  </div>
  <div>
    <label for="color">サイト希望イメージ</label>
    <select multiple name="color" id="color">
    <option value="red">赤</option>
    <option value="blue">青</option>
    <option value="green">緑</option>
    <option value="black">黒</option>
    <option value="White">白</option>
    <option value="pink">ピンク</option>
    <option value="orange">オレンジ</option>
    <option value="others">その他</option>
  </select>
</div>
  <div>
    <label for="color_text">希望イメージのその他</label>
    <input type="text" id="color_text" name="color_text">
  </div>
  <div>
    <label for="business">事業内容</label>
    <input type="text" id="business" name="business">
  </div>
  <div>
    <label for="menu">取扱い商材（メニュー）</label>
    <input type="text" id="menu" name="menu">
  </div>
  <div>
    <label for="strength">自社（自店舗）の強み</label>
    <input type="text" id="strength" name="strength">
  </div>
  <div>
    <label for="keyword">サイトに記載されたいキーワード</label>
    <input type="text" id="keyword" name="keyword">
  </div>
  <div>
    <label for="image_data">使用する画像とロゴデータ</label>
    <input type="file" id="image_data" name="image_data">
  </div>
    <div>
      <input type="checkbox" id="agree" />
      <label for="agree"><a href="{% url 'instaformapp:privacy-policy' %}">プライバシーポリシー</a>に同意する</label>
    </div>
    <div>
      <input type="checkbox" id="agree" />
      <label for="agree"><a href="{% url 'instaformapp:terms' %}">利用規約</a>に同意する</label>
    </div>

  <div>
    <p>ホームページプラン</p>
    <label for="True">ミニマム</label>
    <input type="radio" id="True" name="hp_plan" value="premire"><br>
    <label for="False">ベーシック</label>
    <input type="radio" id="False" name="hp_plan" value="midle">
  </div>
  <script type="text/javascript" src="https://checkout.pay.jp/" class="payjp-button"
  data-key="pk_test_790fb82b7fad88e350c7d3b8" data-submit-text="カードを登録する">
  </script>
</form>

{% endblock content %}

templates/insta_form.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <div>
    <label for="email">ご連絡先メールアドレス</label>
    <input type="email" id="email" name="email">
  </div>
  <div>
    <label for="pass">パスワード</label>
    <input type="password" id="password" name="password">
  </div>
  <div>
    <label for="agency_id">代理店ID</label>
    <input type="text" id="agency_id" name="agency_id">
  </div>
  <div>
    <label for="name">名前</label>
    <input type="text" id="name" name="name">
  </div>
  <div>
    <label for="name_ruby">フリガナ</label>
    <input type="text" id="name_ruby" name="name_ruby">
  </div>
  <div>
    <label for="phone">電話番号</label>
    <input type="tel" id="phone" name="phone">
  </div>
  <div>
    <label for="post">郵便番号</label>
    <input type="text" id="post" name="post">
  </div>
  <div>
    <label for="prefectures">都道府県</label>
    <input type="text" id="prefectures" name="prefectures">
  </div>
  <div>
    <label for="address">住所</label>
    <input type="text" id="address" name="address">
  </div>
  <div>
    <label for="insta_id">インスタアカウント名</label>
    <input type="text" id="insta_id" name="insta_id">
  </div>
  <div>
    <label for="insta_pass">インスタパスワード</label>
    <input type="text" id="insta_pass" name="insta_pass">
  </div>
  <div>
    <input type="checkbox" id="agree" />
    <label for="agree"><a href="{% url 'instaformapp:privacy-policy' %}">プライバシーポリシー</a>に同意する</label>
  </div>
  <div>
    <input type="checkbox" id="agree" />
    <label for="agree"><a href="{% url 'instaformapp:terms' %}">利用規約</a>に同意する</label>
  </div>

  <div>
    <p>インスタプラン</p>
    <label for="True">ミニマム</label>
    <input type="radio" id="True" name="insta_plan" value="premire"><br>
    <label for="False">ベーシック</label>
    <input type="radio" id="False" name="insta_plan" value="midle">
  </div>
  
  <script type="text/javascript" src="https://checkout.pay.jp/" class="payjp-button"
    data-key="pk_test_790fb82b7fad88e350c7d3b8" data-submit-text="カードを登録する">
    </script>
</form>

{% endblock content %}

templates/privacy-policy.html
{% extends 'base.html' %}

{% block content %}
<div>
プライバシーポリシー
株式会社CHAPTER TWOは、当社が取り扱う事業を実施する上で、お客様の個人情報がプライバシーを構成する重要な情報であることを深く認識し、業務において個人情報を取り扱う場合には、個人情報に関する法令及び個人情報保護のために定めた社内規定を定め、また、組織体制を整備し、個人情報の適切な保護に努めることにより、お客様を尊重し、当社に対する期待と信頼に応えていきます。
</div>
<div>
個人情報の取得、利用、提供
当社は、事業活動の範囲内で個人情報の利用目的を特定し、その目的達成のために必要な限度で公正かつ適正に個人情報の取得、利用及び提供を行います。また、取得した個人情報の目的外利用をしないよう処置を講じます。
</div>
<div>
法令・規範の遵守
当社は、個人情報に関する法令、国が定める指針、その他の規範及び社会秩序を遵守し、個人情報の適切な保護に努めます。
</div>
<div>
個人情報の適切な管理
当社は、私たちが取り扱う個人情報について、不正アクセス、紛失、破壊、改ざん、漏えいなどの危険を十分に認識し、合理的な安全対策を実施するとともに、問題が発生した場合は適切な是正措置を講じます。
</div>
<div>
問い合わせへの対応
当社は、私たちが取り扱う個人情報について、本人から開示、訂正、利用停止及び苦情相談等のお問い合わせがあった場合は適正に対応します。
</div>
<div>
継続的改善
当社は、個人情報保護に関する管理規定及び管理体制を整備し、全社員で徹底して運用するとともに定期的な見直しを行い、継続的な改善に努めます。
2018年6月13日　制定
2020年4月16日　改定
株式会社CHAPTER TWO
代表取締役　西原　一貴
</div>
<div>
＜個人情報保護に関する連絡先＞
個人情報問合せ窓口
個人情報保護管理者　眞鍋 良介
TEL06-6599-9279　
</div>
<div>
当社が取扱う個人情報について
当社では「個人情報保護方針」に基づき個人情報の適切な保護に取り組んでいます。当社が事業の用に供するために取得し、または保有する個人情報について、以下の通りお知らせいたします。
</div>
<div>
（１）個人情報の取扱事業者の名称
　　　株式会社CHAPTER TWO
</div>
<div>
（２）個人情報保護管理者（若しくはその代理人）の氏名又は職名、所属及び連絡先
　　　個人情報保護管理者：総務担当
　　　電話番号：06-6599-9279
</div>
<div>
（３）個人情報の利用目的
　　　当社が事業活動において取扱う個人情報の利用目的は、次の通りといたします。
</div>
保有個人データ
個人情報の種別

利用目的

取引先情報

業務管理、各種連絡、請求、支払い管理のため

従業者情報

従業者管理に係わる業務に利用するため（業務・労務・人事管理業務、給与関連業務、福利厚生業務など）

採用応募者情報

採用に係わる業務に利用するため（採用に関する情報提供、採用可否判断、採用業務に関する連絡など）

退職者情報

退職者との連絡、退職者からのお問合せへの対応に利用するため

お問合せ者情報

お問合せに回答するため

本人および代理人の情報（開示等請求時）

開示等の求めに回答するため

 その他、個別に書面で明示したとおりの利用目的とします。

②それ以外取得個人情報

個人情報の種別

利用目的

受託した業務により取得した個人情報

契約及びそれに伴う連絡、アフターケアなどに利用するため

求人サイトから取得した情報

求人者に対する採用の可否を判断・通知するため

（４）個人情報に関するお問合せ窓口
　　　保有個人データに関わるものを含め、個人情報の取扱についての苦情・相談、問合せは、
　　　下記の【問合せ窓口】までお申し出ください。

（５）所属する認定個人情報保護団体の名称および苦情の解決の申し出先
　　　なし

（６）開示等の手続について
当社では、保有個人データに関して、ご本人の開示等（利用目的の通知、開示、内容の訂正、追加又は削除、利用の停止、消去及び第三者への提供の停止）の請求に迅速に対応いたします。希望される場合には、お申し出いただいた方がご本人或いはその代理人であることを確認した上で、合理的な期間及び範囲で対応いたします。

（７）開示等の受付方法・窓口
保有個人データに関する開示等のお申し出は、下記の受付窓口までご連絡ください。ご連絡いただきましたら、当社所定の「保有個人データ開示等請　　求書」を郵送または、FAX、メール等でお送り致しますので、記入の上、必要書類を同封し送付にてお申し込み下さい。（送付料は請求者のご負担となります。）

ご本人（または代理人）であることを確認した上で、書面の交付により回答いたします。なお、この方法によらない開示等の求めには応じられない場合がありますのでご了承下さい。

【問合せ窓口】

窓口の名称

個人情報問合せ窓口

連絡先

窓口責任者：総務担当

住所：大阪府大阪市中央区心斎橋1-13-8 The Place 6F_L

電話：06-6599-9279
</div>
{% endblock content %}

templates/root.html
{% extends 'base.html' %}

{% block content %}

<div>
  <input type="checkbox" id="agree" />
  <label for="agree"><a href="{% url 'instaformapp:form' %}">インスタフォーム</a></label>
</div>

<div>
  <input type="checkbox" id="agree" />
  <label for="agree"><a href="{% url 'hpformapp:form' %}">HPフォーム</a></label>
</div>


{% endblock content %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
{{ message}}

{% endblock content %}